using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace AssignmentSystem.Api.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("202608130001_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        CREATE TABLE "Courses" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL
        );
        CREATE TABLE "Subjects" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL
        );
        CREATE TABLE "Users" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "Email" text NOT NULL,
            "PasswordHash" text NOT NULL,
            "Role" integer NOT NULL,
            "CourseId" integer NULL REFERENCES "Courses" ("Id")
        );
        CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
        CREATE INDEX "IX_Users_CourseId" ON "Users" ("CourseId");
        CREATE TABLE "TeacherCourses" (
            "TeacherId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
            "CourseId" integer NOT NULL REFERENCES "Courses" ("Id") ON DELETE CASCADE,
            "SubjectId" integer NOT NULL REFERENCES "Subjects" ("Id") ON DELETE CASCADE,
            PRIMARY KEY ("TeacherId", "CourseId", "SubjectId")
        );
        CREATE INDEX "IX_TeacherCourses_CourseId" ON "TeacherCourses" ("CourseId");
        CREATE INDEX "IX_TeacherCourses_SubjectId" ON "TeacherCourses" ("SubjectId");
        CREATE TABLE "Assignments" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Title" text NOT NULL,
            "Description" text NOT NULL,
            "DeadlineUtc" timestamp with time zone NOT NULL,
            "MaximumMarks" integer NOT NULL,
            "Status" integer NOT NULL,
            "AllowUpdates" boolean NOT NULL,
            "TeacherId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT,
            "CourseId" integer NOT NULL REFERENCES "Courses" ("Id") ON DELETE CASCADE,
            "SubjectId" integer NOT NULL REFERENCES "Subjects" ("Id") ON DELETE CASCADE
        );
        CREATE INDEX "IX_Assignments_TeacherId" ON "Assignments" ("TeacherId");
        CREATE INDEX "IX_Assignments_CourseId" ON "Assignments" ("CourseId");
        CREATE INDEX "IX_Assignments_SubjectId" ON "Assignments" ("SubjectId");
        CREATE TABLE "Submissions" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Answer" text NOT NULL,
            "SubmittedAtUtc" timestamp with time zone NOT NULL,
            "UpdatedAtUtc" timestamp with time zone NOT NULL,
            "Marks" integer NULL,
            "Feedback" text NULL,
            "Status" integer NOT NULL,
            "AssignmentId" integer NOT NULL REFERENCES "Assignments" ("Id") ON DELETE CASCADE,
            "StudentId" integer NOT NULL REFERENCES "Users" ("Id") ON DELETE RESTRICT
        );
        CREATE UNIQUE INDEX "IX_Submissions_AssignmentId_StudentId" ON "Submissions" ("AssignmentId", "StudentId");
        CREATE INDEX "IX_Submissions_StudentId" ON "Submissions" ("StudentId");
        """);

    protected override void Down(MigrationBuilder migrationBuilder) => migrationBuilder.Sql("""
        DROP TABLE IF EXISTS "Submissions";
        DROP TABLE IF EXISTS "TeacherCourses";
        DROP TABLE IF EXISTS "Assignments";
        DROP TABLE IF EXISTS "Subjects";
        DROP TABLE IF EXISTS "Users";
        DROP TABLE IF EXISTS "Courses";
        """);
}
